# Generated by Django 2.2.6 on 2019-11-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(max_length=200, unique=True)),
                ('restaurant_name', models.CharField(max_length=500)),
                ('cuisines', models.CharField(max_length=2000)),
                ('avg_cost_for_two', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=500)),
                ('has_table_booking', models.CharField(max_length=100)),
                ('has_online_booking', models.CharField(max_length=100)),
                ('agg_rating', models.CharField(max_length=100)),
                ('rating_color', models.CharField(max_length=1000)),
                ('rating_text', models.CharField(max_length=2000)),
                ('votes', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=2000)),
                ('locality', models.CharField(max_length=2000)),
                ('locality_verb', models.CharField(max_length=2000)),
                ('longitude', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('restaurant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants_finder.Restaurants')),
            ],
        ),
    ]
