# Generated by Django 2.2.6 on 2019-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_finder', '0002_auto_20191103_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='agg_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='avg_cost_for_two',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
